name: CI (Functions)
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/functions.continuous-integration.yml'
      - 'packages/functions/**'
      - 'package.json'
jobs:
  install-dependencies:
    name: 'Install >'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        scope: ['functions']
        script: ['lint', 'format', 'build', 'test:ci']
    steps:
      - name: test0r
        run: pwd
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: test1r
        run: echo $HOME $GITHUB_WORKSPACE
      - name: Setup node v10.x environment
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Restore lerna-style dependencies
        uses: actions/cache@master
        id: lerna_cache
        with:
          path: |
            node_modules
            packages/functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/functions/yarn.lock') }}
      - name: Install root package dependencies
        run: yarn install
        if: steps.lerna_cache.outputs.cache-hit != 'true'
      - name: Install inner package dependencies
        run: yarn bootstrap --scope ${{ matrix.scope }}
        if: steps.lerna_cache.outputs.cache-hit != 'true'
      - name: Run ${{ matrix.script }} on inner packages code
        run: yarn run ${{ matrix.script }} --scope ${{ matrix.scope }}
